
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Gadgeteer Designer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Gadgeteer;
using GTM = Gadgeteer.Modules;

namespace Via_prototype
{
    public partial class Program : Gadgeteer.Program
    {
        // GTM.Module definitions
        Gadgeteer.Modules.GHIElectronics.WiFi_RS21 wifi;
        Gadgeteer.Modules.GHIElectronics.Extender extender;
        Gadgeteer.Modules.Seeed.Accelerometer accelerometer;
        Gadgeteer.Modules.Seeed.Compass compass;
        Gadgeteer.Modules.Seeed.GPS gps;
        Gadgeteer.Modules.GHIElectronics.UsbClientDP usbClientDP;

        public static void Main()
        {
            //Important to initialize the Mainboard first
            Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();			

            Program program = new Program();
            program.InitializeModules();
            program.ProgramStarted();
            program.Run(); // Starts Dispatcher
        }

        private void InitializeModules()
        {   
            // Initialize GTM.Modules and event handlers here.		
            usbClientDP = new GTM.GHIElectronics.UsbClientDP(1);
		
            compass = new GTM.Seeed.Compass(4);
		
            wifi = new GTM.GHIElectronics.WiFi_RS21(9);
		
            accelerometer = new GTM.Seeed.Accelerometer(10);
		
            gps = new GTM.Seeed.GPS(11);
		
            extender = new GTM.GHIElectronics.Extender(14);

        }
    }
}
